// This file is generated by Firebase Extensions.
'use server';

/**
 * @fileOverview Replays captured keystrokes with realistic typing speed and pauses.
 *
 * - replayInput - A function that replays the captured keystrokes.
 * - ReplayInputInput - The input type for the replayInput function.
 * - ReplayInputOutput - The return type for the replayInput function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const ReplayInputInputSchema = z.object({
  keystrokes: z
    .string()
    .describe('The captured keystrokes to replay.'),
});
export type ReplayInputInput = z.infer<typeof ReplayInputInputSchema>;

const ReplayInputOutputSchema = z.string().describe('Confirmation that the input was replayed.');
export type ReplayInputOutput = z.infer<typeof ReplayInputOutputSchema>;

export async function replayInput(input: ReplayInputInput): Promise<ReplayInputOutput> {
  return replayInputFlow(input);
}

const prompt = ai.definePrompt({
  name: 'replayInputPrompt',
  input: {schema: ReplayInputInputSchema},
  output: {schema: ReplayInputOutputSchema},
  prompt: `You are an automated input system that will replay the provided keystrokes.

  Simulate realistic typing speed and pauses for each character.  You do not actually replay the input, just indicate that it would be replayed.

  Keystrokes: {{{keystrokes}}}
  `,
});

const replayInputFlow = ai.defineFlow(
  {
    name: 'replayInputFlow',
    inputSchema: ReplayInputInputSchema,
    outputSchema: ReplayInputOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
